# docker-compose up --build --abort-on-container-exit

version: '3.7'

networks:
  arithmetic-expression-network:
  
services:
  integration-tests:
    container_name: arithmetic-expression-tests
    build:
     context: .
     dockerfile: tests.Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Empty"

    command: 
      - /bin/bash
      - -c
      - |
        dotnet test --logger:"html;LogFileName=/src/tests-results/unit_tests.html" ArithmeticExpression.Bff/ArithmeticExpression.Bff.csproj &&
        dotnet test --logger:"html;LogFileName=/src/tests-results/integration_tests.html" ArithmeticExpression.IntegrationTests/ArithmeticExpression.IntegrationTests.csproj
    volumes:
      -  ./:/src/tests-results/
    networks:
      - arithmetic-expression-network
    extra_hosts:
      - "host.docker.internal:host-gateway"


